"""Explicit Conversational pipeline."""

from agent_runtime.operator.models import (
    CodeGenerationCritique,
    DeliberationFrame,
    EvidenceSatisfactionReview,
    OperatorAction,
    OperatorClarificationDecision,
    OperatorClarificationOption,
    OperatorClarificationRequest,
    OperatorParameterClarificationChoice,
    OperatorClarificationStrategy,
    OperatorComputationCacheDecision,
    OperatorDependency,
    OperatorExecutionRecord,
    OperatorFailureContinuationReview,
    OperatorInteractionMode,
    OperatorStepValidationContract,
    OperatorStepValidationReview,
    OperatorFollowupDecision,
    OperatorInputBinding,
    OperatorPipelineResult,
    OperatorPlan,
    OperatorPolicyDecision,
    OperatorPolicyDecisionName,
    OperatorPolicyMode,
    OperatorPolicyModule,
    OperatorPolicyReviewRequest,
    OperatorPolicyReviewResult,
    OperatorPolicySubject,
    PlanCritique,
    OperatorRepair,
    OperatorRepairAdjudication,
    OperatorRephraseRetryProposal,
    OperatorSelfBrief,
    OperatorSelfQuestionAnswer,
    OperatorTask,
    OperatorTryoutCapsule,
    OperatorTryoutCapsuleBatch,
    OperatorTryoutResultReview,
    OperatorVerificationContract,
    ValidationAdjudication,
)
from agent_runtime.operator.effects import (
    ActionEffect,
    classify_action_effect,
    classify_python_effect,
    classify_shell_effect,
    classify_task_effect,
)
from agent_runtime.operator.policy import (
    OPERATOR_POLICY_MODES,
    OPERATOR_POLICY_MODULES,
    normalize_operator_policy_mode,
    review_operator_policy_subjects,
)


def __getattr__(name: str):
    """Lazily expose pipeline classes without import cycles."""

    if name in {"LLMOperatorPipeline", "OperatorPlanValidator"}:
        from agent_runtime.operator.pipeline import LLMOperatorPipeline, OperatorPlanValidator

        return {
            "LLMOperatorPipeline": LLMOperatorPipeline,
            "OperatorPlanValidator": OperatorPlanValidator,
        }[name]
    raise AttributeError(name)

__all__ = [
    "LLMOperatorPipeline",
    "ActionEffect",
    "classify_action_effect",
    "classify_python_effect",
    "classify_shell_effect",
    "classify_task_effect",
    "CodeGenerationCritique",
    "DeliberationFrame",
    "EvidenceSatisfactionReview",
    "OperatorAction",
    "OperatorClarificationDecision",
    "OperatorClarificationOption",
    "OperatorClarificationRequest",
    "OperatorParameterClarificationChoice",
    "OperatorClarificationStrategy",
    "OperatorComputationCacheDecision",
    "OperatorDependency",
    "OperatorExecutionRecord",
    "OperatorFailureContinuationReview",
    "OperatorInteractionMode",
    "OperatorStepValidationContract",
    "OperatorStepValidationReview",
    "OperatorFollowupDecision",
    "OperatorInputBinding",
    "OperatorPipelineResult",
    "OperatorPlan",
    "OperatorPlanValidator",
    "OperatorPolicyDecision",
    "OperatorPolicyDecisionName",
    "OperatorPolicyMode",
    "OperatorPolicyModule",
    "OperatorPolicyReviewRequest",
    "OperatorPolicyReviewResult",
    "OperatorPolicySubject",
    "OPERATOR_POLICY_MODES",
    "OPERATOR_POLICY_MODULES",
    "normalize_operator_policy_mode",
    "review_operator_policy_subjects",
    "PlanCritique",
    "OperatorRepair",
    "OperatorRepairAdjudication",
    "OperatorRephraseRetryProposal",
    "OperatorSelfBrief",
    "OperatorSelfQuestionAnswer",
    "OperatorTask",
    "OperatorTryoutCapsule",
    "OperatorTryoutCapsuleBatch",
    "OperatorTryoutResultReview",
    "OperatorVerificationContract",
    "ValidationAdjudication",
]
