"""Operator pipeline event names."""

from __future__ import annotations

# ruff: noqa: F401,F403,F405

OPERATOR_STAGE = "llm_operator"
OPERATOR_PLAN_PROPOSED = "operator.plan.proposed"
OPERATOR_VALIDATION_ACCEPTED = "operator.validation.accepted"
OPERATOR_VALIDATION_REJECTED = "operator.validation.rejected"
OPERATOR_VALIDATION_ADJUDICATED = "operator.validation.adjudicated"
OPERATOR_APPROVAL_REQUIRED = "operator.approval.required"
OPERATOR_TRYOUT_CANDIDATE = "operator.tryout.candidate"
OPERATOR_TRYOUT_ACCEPTED = "operator.tryout.accepted"
OPERATOR_TRYOUT_EXECUTING = "operator.tryout.executing"
OPERATOR_TRYOUT_OUTPUT = "operator.tryout.output"
OPERATOR_TRYOUT_FAILED = "operator.tryout.failed"
OPERATOR_TRYOUT_REPAIRING = "operator.tryout.repairing"
OPERATOR_TRYOUT_BLOCKED = "operator.tryout.blocked"
OPERATOR_TRYOUT_COMPLETED = "operator.tryout.completed"
OPERATOR_CLARIFICATION_DECISION = "operator.clarification.decision"
OPERATOR_CLARIFICATION_REQUIRED = "operator.clarification.required"
OPERATOR_EXECUTION_STARTED = "operator.execution.started"
OPERATOR_EXECUTION_COMPLETED = "operator.execution.completed"
OPERATOR_EXECUTION_FAILED = "operator.execution.failed"
OPERATOR_REPAIR_PROPOSED = "operator.repair.proposed"
OPERATOR_REPAIR_ACCEPTED = "operator.repair.accepted"
OPERATOR_REPAIR_REJECTED = "operator.repair.rejected"
OPERATOR_REPAIR_ADJUDICATED = "operator.repair.adjudicated"
OPERATOR_REPAIR_ADJUDICATION_SKIPPED = "operator.repair.adjudication_skipped"
OPERATOR_AUTO_REPHRASE_RETRY = "operator.auto_rephrase_retry"
OPERATOR_SELF_BRIEF_COMPLETED = "operator.self_brief.completed"
OPERATOR_PLAN_REVIEW_PROPOSED = "operator.plan_review.proposed"
OPERATOR_PLAN_REVIEW_ACCEPTED = "operator.plan_review.accepted"
OPERATOR_PLAN_REVIEW_REJECTED = "operator.plan_review.rejected"
OPERATOR_MEMORY_COMPLIANCE_REVIEWED = "operator.memory_compliance.reviewed"
OPERATOR_MEMORY_COMPLIANCE_REPAIRED = "operator.memory_compliance.repaired"
OPERATOR_MEMORY_COMPLIANCE_REJECTED = "operator.memory_compliance.rejected"
OPERATOR_INTERACTION_NORMALIZED = "operator.interaction.normalized"
OPERATOR_COMPLETION_REVIEW_PROPOSED = "operator.completion_review.proposed"
OPERATOR_COMPLETION_REVIEW_ACCEPTED = "operator.completion_review.accepted"
OPERATOR_COMPLETION_REVIEW_CONTINUATION = "operator.completion_review.continuation"
OPERATOR_STEP_VALIDATION_PROPOSED = "operator.step_validation.proposed"
OPERATOR_STEP_VALIDATION_ACCEPTED = "operator.step_validation.accepted"
OPERATOR_STEP_VALIDATION_REJECTED = "operator.step_validation.rejected"
OPERATOR_PYTHON_CODE_REVIEW_PROPOSED = "operator.python_code.review_proposed"
OPERATOR_PYTHON_CODE_REVIEW_ACCEPTED = "operator.python_code.review_accepted"
OPERATOR_PYTHON_CODE_REVIEW_REJECTED = "operator.python_code.review_rejected"
OPERATOR_DELIBERATION_STARTED = "operator.deliberation.started"
OPERATOR_DELIBERATION_REVIEWED = "operator.deliberation.reviewed"
OPERATOR_DELIBERATION_REPAIRED = "operator.deliberation.repaired"
OPERATOR_DELIBERATION_AUDIT_FEEDBACK = "operator.deliberation.audit_feedback"
OPERATOR_DELIBERATION_SKIPPED = "operator.deliberation.skipped"
OPERATOR_CLARIFICATION_REJECTED = "operator.clarification.rejected"
OPERATOR_CONVERSATION_CONTEXT_BUILT = "operator.conversation.context_built"
OPERATOR_CONVERSATION_CONTEXT_TRUNCATED = "operator.conversation.context_truncated"
OPERATOR_CONVERSATION_FOLLOWUP_DECISION = "operator.conversation.followup_decision"
OPERATOR_CONVERSATION_ANSWER_FROM_CONTEXT = "operator.conversation.answer_from_context"
OPERATOR_CONVERSATION_PLAN_PROPOSED = "operator.conversation.plan_proposed"
OPERATOR_PLAN_CACHE_LOOKUP = "operator.cache.lookup"
OPERATOR_PLAN_CACHE_HIT = "operator.cache.hit"
OPERATOR_PLAN_CACHE_WRITE = "operator.cache.write"
OPERATOR_PLAN_CACHE_REJECTED = "operator.cache.rejected"
OPERATOR_COMPUTATION_CACHE_LOOKUP = "operator.computation_cache.lookup"
OPERATOR_COMPUTATION_CACHE_HIT = "operator.computation_cache.hit"
OPERATOR_COMPUTATION_CACHE_WRITE = "operator.computation_cache.write"
OPERATOR_COMMAND_TEMPLATE_CACHE_LOOKUP = "operator.command_template_cache.lookup"
OPERATOR_COMMAND_TEMPLATE_CACHE_HIT = "operator.command_template_cache.hit"
OPERATOR_COMMAND_TEMPLATE_CACHE_WRITE = "operator.command_template_cache.write"
OPERATOR_LRDIRECT_LOOKUP = "operator.lrdirect.lookup"
OPERATOR_LRDIRECT_HIT = "operator.lrdirect.hit"
OPERATOR_LRDIRECT_REJECTED = "operator.lrdirect.rejected"
OPERATOR_LRDIRECT_WRITE = "operator.lrdirect.write"
OPERATOR_MEMORY_DIGEST_PROPOSED = "operator.memory_digest.proposed"
OPERATOR_MEMORY_CHECK = "memory_check"

__all__ = [name for name in globals() if name.startswith("OPERATOR_")]
