"""Linux gateway model compatibility wrapper."""

from gateway_core.models import (
    CapabilitiesResponse,
    CapabilityInfo,
    ExecCancelRequest,
    ExecCancelResponse,
    ExecRequest,
    ExecResponse,
    ExecStreamEvent,
    HealthResponse,
    LlmRuntimeLogResponse,
    LlmRuntimeStartRequest,
    LlmRuntimeStatusResponse,
    LlmRuntimeStopRequest,
    RestartRequest,
    RestartResponse,
    TerminalClientMessage,
    TerminalDetachedExecResponse,
    TerminalExecRequest,
    TerminalSessionRequest,
    TerminalSessionResponse,
    TerminalWriteRequest,
)

__all__ = [
    "CapabilitiesResponse",
    "CapabilityInfo",
    "ExecCancelRequest",
    "ExecCancelResponse",
    "ExecRequest",
    "ExecResponse",
    "ExecStreamEvent",
    "HealthResponse",
    "LlmRuntimeLogResponse",
    "LlmRuntimeStartRequest",
    "LlmRuntimeStatusResponse",
    "LlmRuntimeStopRequest",
    "RestartRequest",
    "RestartResponse",
    "TerminalClientMessage",
    "TerminalDetachedExecResponse",
    "TerminalExecRequest",
    "TerminalSessionRequest",
    "TerminalSessionResponse",
    "TerminalWriteRequest",
]
