"""Persistent agent memory subsystem."""

from agent_runtime.memory.models import (
    MemoryAuditEvent,
    MemoryContextDraftRequest,
    MemoryContextDraftResponse,
    MemoryDraftProposal,
    MemoryDraftResponse,
    MemoryDirective,
    MemoryDirectiveStrength,
    MemoryDirectiveTarget,
    MemoryEntry,
    MemoryEntryCreate,
    MemoryEntryUpdate,
    MemoryFeedbackDraftRequest,
    MemoryFeedbackDraftResponse,
    MemoryFeedbackRequest,
    MemoryKind,
    MemoryOptimizationRequest,
    MemoryProposal,
    MemoryRetrievalContext,
    MemoryRetrievalMatch,
    MemoryRunFeedback,
)
from agent_runtime.memory.context import MemoryRetrievalHints, enrich_memory_retrieval_hints
from agent_runtime.memory.guard_rules import (
    evaluate_memory_guard_rules,
    memory_guard_rule_summaries,
)
from agent_runtime.memory.prompting import (
    memory_directives_from_entries,
    memory_directives_for_prompt_stage,
    memory_prompt_lines_from_context,
)
from agent_runtime.memory.scoping import (
    ACTIVE_SCOPE_KEY,
    SCOPED_CACHE_KEY,
    SCOPED_TRACE_KEY,
    active_scope_raw_directives,
    cached_memory_scope,
    memory_scope_from_matches,
    memory_scope_tuple,
    record_scope_memory_question_skip,
    record_scope_prompt_render,
    scope_observability_details,
    scoped_current_task,
    scoped_current_task_id,
    scoped_empty_memory_scope,
    scoped_memory_enabled,
    scoped_memory_scope_id,
    scoped_memory_tags,
    scoped_retrieval_prompt,
    set_active_memory_scope,
    update_memory_scope_trace,
)
from agent_runtime.memory.store import AgentMemoryStore, normalize_model_family

__all__ = [
    "AgentMemoryStore",
    "MemoryAuditEvent",
    "MemoryContextDraftRequest",
    "MemoryContextDraftResponse",
    "MemoryDraftProposal",
    "MemoryDraftResponse",
    "MemoryDirective",
    "MemoryDirectiveStrength",
    "MemoryDirectiveTarget",
    "MemoryEntry",
    "MemoryEntryCreate",
    "MemoryEntryUpdate",
    "MemoryFeedbackDraftRequest",
    "MemoryFeedbackDraftResponse",
    "MemoryFeedbackRequest",
    "MemoryKind",
    "MemoryOptimizationRequest",
    "MemoryProposal",
    "MemoryRetrievalContext",
    "MemoryRetrievalMatch",
    "MemoryRunFeedback",
    "MemoryRetrievalHints",
    "ACTIVE_SCOPE_KEY",
    "SCOPED_CACHE_KEY",
    "SCOPED_TRACE_KEY",
    "active_scope_raw_directives",
    "cached_memory_scope",
    "enrich_memory_retrieval_hints",
    "evaluate_memory_guard_rules",
    "memory_scope_from_matches",
    "memory_scope_tuple",
    "memory_directives_from_entries",
    "memory_directives_for_prompt_stage",
    "memory_guard_rule_summaries",
    "memory_prompt_lines_from_context",
    "normalize_model_family",
    "record_scope_memory_question_skip",
    "record_scope_prompt_render",
    "scope_observability_details",
    "scoped_current_task",
    "scoped_current_task_id",
    "scoped_empty_memory_scope",
    "scoped_memory_enabled",
    "scoped_memory_scope_id",
    "scoped_memory_tags",
    "scoped_retrieval_prompt",
    "set_active_memory_scope",
    "update_memory_scope_trace",
]
